### ISSUE TITLE
reset btn bug

### ISSUE THREAD

**Issue by ToasterCoder44** [BaderBC/tic-tac-toe#1]
Try clicking like this:

![image](https://user-images.githubusercontent.com/105929223/170522191-eabcc03d-fca3-4a5f-a441-8991ed37fbc7.png)

and you will see a bug like this:

![image](https://user-images.githubusercontent.com/105929223/170522453-0dfdc99b-2717-4def-bce8-afa5e5f91785.png)

Don't forget to refresh site before checking issue

**Comment by BaderBC** [comment]
**Thanks for reporting, I've already fixed it ;)**
